import { ScrollUp } from '../assets/icons';
import { Footer } from '../components';
import '../styles/docs.scss';

/**
 * A view for the Terms of Use
 */
export const TermsOfUse = () => {
  const scrollTop = () => window.scrollTo(0, 0);
  return (
    <div>
      <div className="docs pt-8">
        <div className="docs-title">Terms of Use</div>
        <div className="docs-updated">Last updated: July 27, 2021</div>
        <div className="docs-text">
          <p>Acceptance of the Terms of Use</p>
          <p>These terms of use are entered into by and between You and REEF Technology Inc. and its subsidiaries and affiliates (&ldquo;REEF,&rdquo; &ldquo;we,&rdquo; or &ldquo;us&rdquo;). The following terms and conditions, together with any documents they expressly incorporate by reference (collectively, &ldquo;Terms of Use&rdquo;), govern (i) your access to and use of our U.S. and Canadian websites, including any content, functionality, and services offered on or through our U.S. and Canadian websites (the &ldquo;Websites&rdquo;), whether as a guest or a registered user, (ii) your use of REEF&rsquo;s mobile applications (each and collectively an &ldquo;App&rdquo;), and (iii) your use or receipt of any content, functionality, service, technology, good, or product provided to you by REEF (each a &ldquo;Service&rdquo; and collectively the &ldquo;Service&rdquo;). The Websites, App and Service are together referred to throughout these Terms of Use as the &ldquo;REEF Services.&rdquo; <br /><br />
            IMPORTANT: THESE TERMS OF USE CONTAINS A MANDATORY ARBITRATION PROVISION THAT, AS FURTHER SET FORTH IN SECTION 18 BELOW AND WITH LIMITED EXCEPTIONS, REQUIRES THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES RATHER THAN JURY TRIALS, INCLUDING CLASS ACTION LAWSUITS, IN COURTS AND ONLY SPECIFIC REMEDIES ARE AVAILABLE TO YOU.<br /><br />
            Please read the Terms of Use carefully before you start to use the REEF Services. By using the REEF Services, you accept and agree to be bound and abide by these Terms of Use and our Privacy Policy, found at https://www.reeftechnology.com/privacy-policy/ (the &ldquo;Privacy Policy&rdquo;), incorporated herein by reference. Each time you access or use the REEF Services, you agree to be bound by the Terms of Use along with our Privacy Policy and any additional guidelines, terms, procedures or rules that may apply to a specific feature of the REEF Services. If you do not want to agree to these Terms of Use or the Privacy Policy, you must not access or use the REEF Services. <br /><br />
            By using the REEF Services, you warrant that you are of legal age to form a binding contract with REEF and meet all of the eligibility requirements in this Terms of Use. If you do not meet all of these requirements, you must not access or use the REEF Services. <br /><br />
            1. Changes to the Terms of Use<br /><br />
            We may revise and update these Terms of Use from time to time in our sole discretion. All changes are effective immediately when we post them and apply to all access to and use of the REEF Services. <br /><br />
            Your continued use of the REEF Services following the posting of revised Terms of Use means that you accept and agree to the changes. <br /><br />
            2. Accessing the REEF Services and Account Security<br /><br />
            You are responsible for making all arrangements necessary for you to have access to the REEF Services and maintaining the accuracy of any information you submit to REEF in relation to your access and use of the REEF Services. <br /><br />
            To access the REEF Services or some of the resources they offer, you may be asked to provide certain registration details or other information. You warrant that all the information you provide on or through the REEF Services is correct, current, and complete. All information you provide to register for the REEF Services or otherwise, including, but not limited to, through the use of any interactive features on the REEF Services, is governed by the Privacy Policy.<br /><br />
            You must treat your username, password, or any other piece of information used as part of our security procedures as confidential. Your account is personal to you and you may not provide any other person with access to the REEF Services or portions of it using your username, password, or other security information. You agree to notify us immediately of any unauthorized access to or use of your account or any other breach of security. If you are accessing or using our Digital Services on behalf of another person or entity, you represent that you are authorized to accept these Terms of Use on that person or entity&rsquo;s behalf and that the person or entity agrees to be responsible to us if you or the other person or entity violates these Terms of Use.<br /><br />
            3. Intellectual and other Property Rights<br /><br />
            The REEF Services and their entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof) are owned by REEF, its licensors, or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws. <br /><br />
            The REEF name and all related names, logos, product and service names, designs, and slogans are trademarks of REEF or its affiliates or licensors. You must not use such marks without the prior written permission of REEF. All other names, logos, product and service names, designs, and slogans on the REEF Services are the trademarks of their respective owners.<br /><br />
            4. Use Rights<br /><br />
            We grant you a non-exclusive, non-sublicensable, revocable, non-transferable license to use and access the REEF Services and the information contained in the REEF Services for your personal, non-commercial use only in accordance with these Terms of Use. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our REEF Services.<br /><br />
            You will not: (a) modify copies of any materials from the REEF Services; (b) use any illustrations, photographs, video or audio sequences, or any graphics separately from the accompanying text; or (c) delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials from this site. <br /><br />
            5. Prohibited Uses<br /><br />
            You will not: (a) monitor, copy, reproduce, modify, adapt or create derivative works of the REEF Services; (b) conduct any systematic retrieval of data or other content from the REEF Services, like creating a deep-link to the REEF Services or accessing the REEF Services with any robot, spider, web crawler, extraction software, automated process and/or device to scrape, copy, index, frame, or monitor any portion of the REEF Services or any content on the REEF Services; (c) transfer, distribute, sell, or sublicense the REEF Services to a third party; (d) incorporate or use the REEF Services into a product or service that you provide to a third party; (e) interfere with or otherwise circumvent mechanisms in the REEF Services intended to limit use or attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the REEF Services, the server on which the REEF Services are stored, or any server, computer, or database connected to the REEF Services; (f) attack the REEF Services via a denial-of-service attack or a distributed denial-of-service attack; (g) reverse engineer, disassemble, decompile, translate or otherwise seek to obtain or derive the source code, underlying ideas, algorithms, file formats or non-public APIs to the REEF Services; (h) remove or alter any proprietary or other notices contained in the REEF Services; (i) use the REEF Services for competitive analysis or to build competitive products; (j) use the REEF Services in any manner that could disable, overburden, damage, or impair the site or interfere with any other party&rsquo;s use of the REEF Services, including their ability to engage in real time activities through the REEF Services; (k) use the REEF Services in any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries), or (l) encourage or assist any third party to do any of the foregoing. <br /><br />
            You will not: (a) use the REEF Services for unlawful, obscene, offensive or fraudulent purposes, (b) input in the REEF Services any information that contains any personal information of minors or that is unlawful, obscene, offensive or violates third party rights; (c) use the REEF Services to exploit or harm individuals; or (d) use the REEF Services to interfere with or violate the integrity or security of a network or system, evading filters, sending unsolicited, abusive or deceptive messages, or viruses or harmful code.<br /><br />
            6. User Contributions<br /><br />
            6.1 General<br /><br />
            The REEF Services may contain message boards, chat rooms, personal web pages or profiles, forums, bulletin boards, and other interactive features (collectively, &ldquo;Interactive Services&rdquo;) that allow users to post, submit, publish, display, or transmit to other users or other persons (hereinafter, &ldquo;post&rdquo;) content or materials (collectively, &ldquo;User Contributions&rdquo;) on or through the REEF Services. <br /><br />
            Any User Contribution you post to the REEF Services will be considered non-confidential and non-proprietary. By providing any User Contribution on the REEF Services, you grant us and our affiliates and service providers, and each of their respective licensees, successors, and assigns the right to use, reproduce, modify, perform, display, distribute, and otherwise disclose to third parties any such material for any purpose. <br /><br />
            You warrant that you own or control all rights in and to the User Contributions and have the right to grant the license granted above. <br /><br />
            You are responsible for any User Contributions you submit or contribute, and you have full responsibility for such content, including its legality, reliability, accuracy, and appropriateness. <br /><br />
            6.2 Content Standards <br /><br />
            These content standards apply to any and all User Contributions and use of Interactive Services. User Contributions must in their entirety comply with all applicable federal, state, local, and international laws and regulations. <br /><br />
            User Contributions must not: (a) promote violence, or discrimination based on race, sex, religion, nationality, disability, sexual orientation, or age; (b) infringe any patent, trademark, trade secret, copyright, or other intellectual property or other rights of any other person; (c) be likely to deceive any person; (d) promote any illegal activity, or advocate, promote, or assist any unlawful act; (e) cause annoyance, inconvenience, or needless anxiety or be likely to upset, embarrass, alarm, or annoy any other person; (f) impersonate any person, or misrepresent your identity or affiliation with any person or organization; (g) involve commercial activities or sales, such as contests, sweepstakes, and other sales promotions, barter, or advertising; or (h) give the impression that they emanate from or are endorsed by us or any other person or entity, if this is not the case. <br /><br />
            6.3 Monitoring and Enforcement; Termination <br /><br />
            We have the right to: (a) remove or refuse to post any User Contributions for any or no reason in our sole discretion; (b) take any action with respect to any User Contribution that we deem necessary or appropriate in our sole discretion, including if we believe that such User Contribution violates the Terms of Use or could create liability for the REEF, (c) disclose your identity or other information about you to any third party who claims that material posted by you violates their rights, including their intellectual property rights or their right to privacy; (d) take appropriate legal action, including without limitation, referral to law enforcement, for any illegal or unauthorized use of the REEF Services; or (e) terminate or suspend your access to all or part of the REEF Services for any or no reason, including without limitation, any violation of these Terms of Use. <br /><br />
            Without limiting the foregoing, we have the right to cooperate fully with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone posting any materials on or through the REEF Services. YOU WAIVE AND HOLD HARMLESS REEF (AND ITS AFFILIATES AND ITS AND THEIR OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS AND AGENTS), LICENSEES, AND SERVICE PROVIDERS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY THEM DURING, OR TAKEN AS A CONSEQUENCE OF, INVESTIGATIONS BY EITHER REEF OR LAW ENFORCEMENT AUTHORITIES. <br /><br />
            We cannot review all material before it is posted on the REEF Services, and cannot ensure prompt removal of objectionable material after it has been posted. Accordingly, we assume no liability for any action or inaction regarding transmissions, communications, or content provided by any user or third party. We have no liability or responsibility to anyone for performance or nonperformance of the activities described in this section. <br /><br />
            7. Reliance on Information Posted<br /><br />
            The information presented on or through the REEF Services is made available solely for general information purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance you place on such information is strictly at your own risk. Information relating to food or beverages should not be used by you to evaluate ingredient information, nutritional values, or potential food allergies. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other user or visitor to the REEF Services, or by anyone who may be informed of any of its contents. <br /><br />
            This REEF Services may include content provided by third parties, including materials provided by other users, bloggers, and third-party licensors, syndicators, aggregators, and/or reporting services. All statements and/or opinions expressed in these materials, and all articles and responses to questions and other content, other than the content provided by REEF, are solely the opinions and the responsibility of the person or entity providing those materials. These materials do not necessarily reflect the opinion of REEF. We are not responsible, or liable to you or any third party, for the content or accuracy of any materials provided by any third parties. <br /><br />
            8. Changes to the REEF Services<br /><br />
            We reserve the right to withdraw or change the REEF Services in our sole discretion without notice. We will not be liable if for any reason all or any part of the REEF Services are unavailable. From time to time, we may restrict access to some or all parts of the Websites or REEF Services. <br /><br />
            We may update the content on the REEF Services from time to time, but its content is not necessarily complete or up to date. Any of the material on the REEF Services may be out of date at any given time, and we are under no obligation to update such material. <br /><br />
            You grant us a perpetual, irrevocable, transferable, non-exclusive right to use any comments, suggestions, ideas or recommendations that you provide related to any of our products or services in any manner and for any purpose.<br /><br />
            9. Information About You and Your Visits to the REEF Services<br /><br />
            All information we collect on the REEF Services are subject to our Privacy Policy located at https://www.reeftechnology.com/privacy-policy/. By using the REEF Services, you consent to all actions taken by us with respect to your information in compliance with the Privacy Policy. Please take a moment to review our Privacy Policy, which is incorporated into this Agreement and forms part of the Agreement. <br /><br />
            10. Contacting You<br /><br />
            You agree that REEF and its representatives, may contact you by text or telephone at the phone numbers that you provide in connection with the REEF Services and your account, to provide the Services, in the event of suspected fraudulent or illegal activities, or for marketing purposes. You understand that you are not required to provide this consent as a condition of purchasing any property, goods or services. You also understand that you may opt out of receiving text messages from us at any time, either by replying &ldquo;STOP&rdquo; or by contacting privacy@reeftechnology.com. If you do not choose to opt out, we may contact you as set forth in our Privacy Policy located at https://www.reeftechnology.com/privacy-policy/.<br /><br />
            11. Linking to the Websites and Social Media Features<br /><br />
            You may link to our Website homepages, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval, or endorsement on our part. <br /><br />
            The REEF Services may provide certain social media features that enable you to: (a) link from your own or certain third-party websites to certain content on the REEF Services; (b) send emails or other communications with certain content, or links to certain content, on the REEF Services; or (c) cause limited portions of content on the REEF Services to be displayed or appear to be displayed on your own or certain third-party websites. <br /><br />
            You may use these features solely as they are provided by us. You will not: (x) establish a link from any website that is not owned by you; (y) cause the REEF Services or portions of it to be displayed on, or appear to be displayed by, any other site, for example, framing, deep linking, or in-line linking; or (z) link to any part of the Websites other than the homepages.<br /><br />
            You agree to cooperate with us in causing any unauthorized framing or linking immediately to stop. We reserve the right to withdraw linking permission without notice. <br /><br />
            We may disable all or any social media features and any links at any time without notice in our discretion. <br /><br />
            12. Links from the REEF Services<br /><br />
            If the REEF Services contain links to other sites and resources provided by third parties, these links are provided for your convenience only. This includes links contained in advertisements, including banner advertisements and sponsored links. We have no control over the contents of those sites or resources, and accept no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third-party websites linked to the REEF Services, you do so entirely at your own risk and subject to the terms and conditions of use for such websites. <br /><br />
            13. Geographic Restrictions<br /><br />
            The owner of the REEF Services is based in the United States. We provide the REEF Services for use only by persons located in the United States and Canada. We make no claims that the REEF Services or any of their content is accessible or appropriate outside of the United States or Canada. Access to the REEF Services may not be legal by certain persons or in certain countries. If you access the REEF Services from outside the United States or Canada, you do so on your own initiative and are responsible for compliance with local laws. <br /><br />
            14. Disclaimer of Warranties<br /><br />
            YOUR USE OF THE REEF SERVICES AND THEIR CONTENT IS AT YOUR OWN RISK. THE REEF SERVICES AND THEIR CONTENT ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. REEF DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE. <br /><br />
            NEITHER REEF NOR ANY PERSON ASSOCIATED WITH REEF MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE REEF SERVICES. WITHOUT LIMITING THE FOREGOING, NEITHER REEF NOR ANYONE ASSOCIATED WITH REEF REPRESENTS OR WARRANTS THAT THE REEF SERVICES AND THEIR CONTENT WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT OUR SITES OR THE SERVERS THAT MAKE THE REEF SERVICES AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT THE REEF SERVICES WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS. <br /><br />
            THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. <br /><br />
            15. Limitation on Liability<br /><br />
            IN NO EVENT WILL REEF, ITS AFFILIATES, OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, OR DIRECTORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE REEF SERVICES, ANY WEBSITES LINKED TO THEM, ANY CONTENT ON THE REEF SERVICES, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE. <br /><br />
            OUR LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR RELATED TO THIS AGREEMENT IN THE AGGREGATE (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (A) FIFTY US DOLLARS ($50) OR (B) AMOUNTS YOU&rsquo;VE PAID REEF IN THE PRIOR TWELVE (12) MONTHS, IF ANY. REEF&rsquo;S SERVICE PROVIDERS WILL HAVE NO LIABILITY OF ANY KIND ARISING FROM OR RELATING TO THIS AGREEMENT. <br /><br />
            ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF USE OR THE REEF SERVICES MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES; OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED. <br /><br />
            THE FOREGOING DOES NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. <br /><br />
            16. Indemnification<br /><br />
            You agree to indemnify, and hold harmless REEF, its affiliates, licensors, and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys&rsquo; fees) arising out of or relating to your violation of these Terms of Use or your use of the REEF Services, including, but not limited to, your User Contributions, any use of the REEF Services&rsquo; content, services and products other than as expressly authorized in these Terms of Use, or your use of any information obtained from the REEF Services. <br /><br />
            17. Governing Law and Jurisdiction<br /><br />
            All matters relating to the REEF Services and these Terms of Use, and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), shall be governed by and construed in accordance with the internal laws of the State of New York, USA without giving effect to any choice or conflict of law provision or rule (whether of the State of New York or any other jurisdiction). <br /><br />
            18. Arbitration and Class Action Waiver<br /><br />
            PLEASE READ THIS SECTION CAREFULLY &ndash; IT AFFECTS YOUR LEGAL RIGHTS AND GOVERNS HOW YOU AND REEF CAN BRING CLAIMS AGAINST EACH OTHER. THIS SECTION WILL, WITH LIMITED EXCEPTION, REQUIRE YOU AND REEF TO SUBMIT CLAIMS AGAINST EACH OTHER TO BINDING AND FINAL ARBITRATION ON AN INDIVIDUAL BASIS. THIS MEANS THAT YOU WILL NOT BE ABLE TO BRING A CLASS, COLLECTIVE, OR REPRESENTATIVE LAWSUIT IN A COURT OF LAW BEFORE A JUDGE OR JURY CONCERNING ANY DISPUTE THAT MAY ARISE WHICH IS COVERED BY THE ARBITRATION AGREEMENT AND ARE INSTEAD AGREEING TO SUBMIT ANY SUCH DISPUTE SOLELY ON YOUR OWN BEHALF TO AN IMPARTIAL ARBITRATOR. <br /><br />
            18.1 Agreement to Arbitrate. You and REEF mutually agree to forego the delay and expense of using a court of law and choose instead to benefit from the speedy, economical, and impartial dispute resolution procedure of using binding arbitration for any &ldquo;Covered Claims&rdquo; (as defined below) that arise between you and REEF, its related and affiliated companies, and/or any current or former employee, officer, or director of REEF or any related or affiliated company. you and REEF agree that this Arbitration and Class Action Waiver Section is governed by the Federal Arbitration Act, 9 U.S.C. &sect; 1 et seq., and will survive even after these Terms of Use and any REEF Services terminate. Any revision to or termination of the Terms of Use that modify or terminate this Arbitration and Class Action Waiver Section shall not apply to a pending arbitration, to any claim that accrued prior to the modification or termination, or to any claim that the asserting party knew about prior to the modification or termination, except as may be required by applicable law. <br /><br />
            18.2 Claims Subject to Arbitration. Other than the exceptions listed below, the &ldquo;Covered Claims&rdquo; include any and all controversies, disputes, disagreements, and claims arising out of, or relating to, these Terms of Use (including its enforcement, breach, performance, interpretation, validity, or termination), or your access to and/or use of the REEF Services, or the provision of content, services, and/or technology on or through the Websites, App or otherwise to the fullest extent allowed by law.. <br /><br />
            18.3 Claims Not Covered by Arbitration, Jurisdiction, and Venue. The Covered Claims do not include (and thus shall not require arbitration of) the following types of claims that will hereafter be referred to as &ldquo;Excluded Claims&rdquo;: (a) any claims that cannot be required to be arbitrated as a matter of law (including but not limited to claims by California residents under the California Private Attorney General Act of 2004 (&ldquo;PAGA&rdquo;), to the extent exclusion from arbitration is required by California law, and claims or charges that must be filed with a governmental administrative agency); (b) applications for provisional remedies, preliminary injunctions, and temporary restraining orders, including but not limited to those relating to actual or threatened infringement, misappropriation, or violation of a party&rsquo;s copyrights, trademarks, trade secrets, patents, or other intellectual property rights; and (c) small claims actions demanding $10,000 or less brought on an individual basis and within a small claims court&rsquo;s jurisdiction. <br /><br />
            Any Excluded Claims arising out of, or related to, these Terms of Use or the REEF Services shall be instituted exclusively in the state and federal courts located in the City of New York and County of New York, New York, which shall be the exclusive forum for such claims. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts. <br /><br />
            In the event you or REEF chooses to pursue arbitration of both Covered Claims and Excluded Claims and the other party objects, the Covered Claims must be arbitrated. In no event will Covered Claims be joined with Excluded Claims and litigated in court unless both parties agree to waive arbitration. <br /><br />
            18.4 Class Action Waiver. Except as otherwise required under applicable law, you and REEF agree to arbitrate any Covered Claims only on an individual basis and hereby waive any right to bring, participate in, or receive money or any other relief from any representative, class, or collective proceeding (&ldquo;Class Action Waiver&rdquo;). No party may bring a claim on behalf of other individuals, and no arbitrator hearing any claim under these Terms of Use may: (a) without the consent of all parties, combine more than one individual&rsquo;s claim or claims into a single case; (b) order, require, participate in, or facilitate production of class-wide contact information or notification of others of potential claims; or (c) arbitrate any form of a class, collective, or representative proceeding. <br /><br />
            18.5 Arbitrability Determinations. If a party violates the agreement to arbitrate by commencing an action asserting a Covered Claim in a court of law, then the court (and not an arbitrator) shall have the authority to resolve any disputes about the interpretation, formation, existence, enforceability, validity, and scope of the this Arbitration and Class Action Waiver Section. If a party complies with the agreement to arbitrate and files for arbitration without filing a complaint in a court of law, then the arbitrator shall have the authority to resolve any disputes about the interpretation of this Arbitration and Class Action Waiver Section for purposes of discovery or the merits of the underlying claim, but shall have no authority to resolve any disputes about the formation, existence, enforceability, or validity of this Arbitration and Class Action Waiver Section, including the Class Action Waiver. <br /><br />
            18.6 Arbitration Rules, Procedures, and Costs. To initiate arbitration, the party desiring to pursue a legal dispute must prepare a written demand setting forth the claim(s) and deliver the written demand within the applicable statute of limitations period by hand or first class mail to the representatives of the other party. You and REEF agree that the arbitration shall be administered by JAMS before a single arbitrator mutually agreed upon by the parties, and if the parties cannot agree within thirty (30) days after names of potential arbitrators have been proposed, then by a single arbitrator who is chosen by JAMS. Except to the extent that they are modified by the rules below, if you are an individual person, the JAMS Streamlined Arbitration Rules &amp; Procedures that are in effect at the time of the filing of the demand (and that are available at https://www.jamsadr.com/rules-streamlined-arbitration/) will apply. Except to the extent that they are modified by the rules below, if you are not an individual person, but are an entity or company, the JAMS Streamlined Arbitration Rules &amp; Procedures that are in effect at the time of the filing of the demand (and that are available at https://www.jamsadr.com/rules-streamlined-arbitration/) will apply. <br /><br />
            18.7 The parties agree that the applicable JAMS rules are modified as follows: <br /><br />
            a. Any arbitrator must be neutral as to all parties. Standards for the recusal of an arbitrator shall be the same standards under which trial judges are recused under New York law. <br /><br />
            b. No party is entitled to its attorneys&rsquo; fees, except as may be awarded in a matter authorized by and consistent with applicable law. <br /><br />
            c. All discovery shall be subject to any and all objections available under FRCP 26(b). Each party shall avoid broad or widespread collection, search, and production of documents, including electronically stored information (&ldquo;ESI&rdquo;). If a compelling need is demonstrated by the requesting party, the production shall: (i) be narrowly tailored in scope; (ii) only come from sources that are reasonably accessible without undue burden or cost; and (iii) be produced in a searchable format, if possible without undue burden or cost, and which is usable by the receiving party and convenient and economical for the producing party. Where the costs and burdens of the requested discovery outweigh its likely benefit, considering the needs of the case, the amount in controversy, and the importance of the discovery in resolving the issues, the arbitrator shall deny such requests or order production on condition that the requesting party advance to the producing party the reasonable costs involved in making the production, subject to the allocation of costs in the final award. <br /><br />
            d. The arbitrator shall have the authority to award the same damages and other relief that would have been available in court pursuant to the law governing the Covered Claim(s). <br /><br />
            e. Either party shall have the right to file motions to dismiss and motions for summary judgment/adjudication. <br /><br />
            f. The arbitrator shall have the authority to issue an award or partial award without conducting a hearing on the grounds that there is no claim on which relief can be granted or that there is no genuine issue of material fact to resolve at a hearing. <br /><br />
            g. The Federal Rules of Evidence shall apply to all arbitration proceedings. <br /><br />
            h. For discovery purposes only, an arbitrator may consolidate claims filed by multiple individuals, each on their own behalf, in a single arbitration proceeding, or may conduct a joint hearing for efficiency purposes, so long as the arbitrator does not (a) certify (conditionally or otherwise) a collective, class, or representative action that includes individuals who have not themselves already submitted their own individual claims, or (b) authorize the issuance of notice of the arbitration to individuals on the grounds that the arbitrator or any party believes there are other individuals who are similarly situated to or share commonality with a party to the arbitration. <br /><br />
            i. The arbitrator must issue a decision in writing, setting forth in summary form the reasons for the arbitrator&rsquo;s determination and the legal basis therefor. <br /><br />
            j. The arbitrator&rsquo;s authority shall be limited to deciding the case submitted by the parties to the arbitration. Therefore, no decision by any arbitrator shall serve as precedent in other arbitrations except to preclude the same claim from being re-arbitrated between the same parties. <br /><br />
            k. The parties may settle any dispute on a mutual basis without involvement of the arbitrator. <br /><br />
            l. If you initiate arbitration, you will pay the first $250, and REEF will pay all other filing, administrative, or hearing fees. If you are an individual person and REEF initiates arbitration, REEF will pay all filing, administrative, and hearing fees. Regardless of which party initiates arbitration, you will remain responsible for your attorneys&rsquo; fees and costs unless the law governing the Covered Claim provides for an award of attorneys&rsquo; fees and costs and the arbitrator determines as part of the arbitration award that you may recover a certain amount of attorneys&rsquo; fees and costs. <br /><br />
            If any term or condition in this Arbitration and Class Action Waiver Section is determined to be unenforceable or in conflict with a mandatory provision of applicable law, it shall be construed to incorporate any mandatory provision, or the unenforceable or conflicting term or condition shall be automatically severed and the remainder of this Arbitration and Class Action Waiver Section shall not be affected. Provided, however, that if the Class Action Waiver is found to be unenforceable, then any claim brought on a class, collective, or representative action basis shall be adjudicated exclusively in the state and federal courts located in the City of New York and County of New York, New York, which shall be the exclusive forum for such claims. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts. <br /><br />
            19. General<br /><br />
            No waiver by REEF of any term or condition set out in these Terms of Use shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of REEF to assert a right or provision under these Terms of Use shall not constitute a waiver of such right or provision. <br /><br />
            If any provision of these Terms of Use is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Use will continue in full force and effect. <br /><br />
            The Terms of Use, our Privacy Policy and any other relevant agreement to the REEF Services constitute the sole and entire agreement between you and REEF regarding the REEF Services and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, regarding the REEF Services. <br /><br />
            20. Additional Terms Applicable to Special REEF Services <br /><br />
            20.1 REEF Logistics Waitlist Services. Any use of the REEF logistics waitlist services (&ldquo;REEF Logistics Waitlist Services&rdquo;), including REEF Q, is subject to the following additional terms: <br /><br />
            a. General. REEF Logistics Waitlist Services, such as REEFQ and other logistics services, may be utilized by third parties to facilitate the scheduling or organization of medical appointments. REEF does not provide medical services nor are we involved in your medical care. WE WILL NOT BE LIABLE, AND YOU AGREE NOT TO HOLD REEF LIABLE, FOR ANY INJURY, LOSS OR DAMAGE THAT MAY RESULT IN CONNECTION WITH MEDICAL SERVICES OR ANY TREATMENT YOU RECEIVE FOLLOWING YOUR USE OF THE REEF SERVICES, INCLUDING BUT NOT LIMITED TO THE REEF LOGISTICS WAITLIST SERVICES. <br /><br />
            20.2 REEF Order and Delivery Services. Any use of REEF&rsquo;s order and delivery services for food and goods (&ldquo;REEF Order and Delivery Services&rdquo;) is subject to the following additional terms: <br /><br />
            a. General. Once you have placed an order for REEF Order and Delivery Services, we will send you an order acknowledgment by email. This is not an order confirmation or acceptance from us. In addition to the price of goods, a delivery charge as shown at checkout, if applicable, will also be payable by you. All prices quoted are exclusive of tax and you will see estimated taxes and fees when you place the order. The final taxes and fees will be calculated on the day you place your order. Title to and risk of loss for the goods purchased by you passes to you upon delivery of the items to the delivery partner. Pricing for REEF Order and Delivery Services and delivery charges may change from time to time at REEF&rsquo;s sole discretion, but pricing and delivery charges will not change after your order has been placed. <br /><br />
            b. Minimum Order. Deliveries may be subject to a minimum order value, which may change from time to time at REEF&rsquo;s sole discretion. <br /><br />
            c. Substitution Policy. If a good becomes unavailable when filling your order, REEF will not substitute the unavailable good for a similar available good, but rather will issue a refund for the unavailable good. In the event that such refund results in an order total below the minimum order threshold, the minimum order requirement will be waived for that order only. <br /><br />
            d. Quantity Limitations. REEF may, for any reason in its sole discretion, limit the quantity of any particular good ordered. This may be for inventory control or other reasons. Product availability is subject to the inventory on hand and may vary geographically or change without notice. We reserve the right to source the goods from any of our facilities in any location (or the facilities of any of our affiliated companies or partners in any location). <br /><br />
            e. Delivery. REEF may use its own personal or third-party partners for delivery of items ordered by you from the REEF Order and Delivery. We will use reasonable efforts to deliver your goods within the time window you select, where available, or in the window provided to you when placing your order, but REEF does not guarantee that goods will be delivered on or by a certain date or time. REEF will not be liable for delivering the goods outside of the delivery time or failing to deliver all or any of the goods in your order. In the case of inclement weather or unforeseen delivery complications, it may be necessary to make adjustments to our delivery schedule which will cause us to suspend or delay delivery dates and times. <br /><br />
            f. Batching. In the event you place more than one order through different REEF Order and Delivery Services, REEF may, at its sole discretion, choose to deliver all orders at the same time or may choose to deliver them separately. If REEF chooses to deliver multiple orders at the same time, you will not be refunded for any delivery fees incurred for individual orders. <br /><br />
            g. Receipt of Delivery. You agree to provide accurate and thorough information related to the delivery location. REEF shall not be liable for delivery to the wrong location or unfulfilled deliveries as a result of you providing REEF with incomplete or inaccurate delivery information. Unattended deliveries may be made in REEF&rsquo;s sole discretion. If REEF elects unattended delivery, your order will be left unattended at your door or another similar location, or at another place designated by you where such ability for you to designate an alternative delivery location is available. REEF is not responsible, and you agree not to hold REEF liable in any way, for any damage, spoilage, or theft that occurs to an unattended delivery. We reserve the right to refuse to leave an order unattended if we consider the circumstances to be unsuitable or unsafe for any reason. Where delivery is made in-person, anyone who receives the delivery at the delivery address is conclusively presumed to be authorized to receive the delivery. Should REEF be unable to deliver your order for any reason, including finding nobody home at the time of our delivery or the unavailability or unsuitability of an unattended delivery location, you will have 24 hours to contact us at support@getreef.com regarding redelivery of your order, and you may be assessed a re-delivery fee if the order is redelivered. Your order is considered forfeited without refund after 24 hours from your delivery window if you have not contacted us to make alternate arrangements within that time frame. <br /><br />
            h. No Refunds. REEF does not offer refunds or credits for goods purchased and delivered. If items in your order were not delivered, or if delivered goods were defective, contact support@getreef.com and please be prepared to show photographic evidence of such, if applicable. <br /><br />
            i. Promo Codes. Promotion codes (&ldquo;Promo Codes&rdquo;) are valid only for REEF Delivery Services orders, subject to the terms of this Section. Your use of a Promo Code indicates your agreement to be bound by these Terms of Use and any Promo Code terms on the promotion offer itself. REEF will only honor a Promo Code if it is used in accordance with all applicable terms. Promo Codes issued by REEF are, and will remain, the property of REEF and are not transferable, cannot be resold, and have no cash value unless otherwise stated. Use of a Promo Code may be subject to you providing proof of entitlement to use the Promo Code. Promo Code values may be adjusted if the total discount value is greater than the value of your order. REEF reserves the right to withdraw or cancel any Promo Code at any time, either as a whole, or for specific goods or delivery areas. If this happens, then the Promo Codes may not be used for any orders placed after the date of withdrawal or cancellation. We reserve the right to reject or cancel the use of a Promo Code where fraud or misuse is suspected. You will have no claim against REEF in connection with such rejection or cancellation of a Promo Code. REEF will not be liable to any customer or household for any financial loss arising out of the cancellation or withdrawal of any Promo Code or any failure or inability of a customer to use a Promo Code for any reason. Promo Codes may not be copied, reproduced, published, or distributed directly or indirectly in any form for use by anyone other than the original recipient. By using a Promo Code, you warrant that you are the duly authorized recipient of it. You may only use one Promo Code for each order unless otherwise stated on the applicable Promo Code. We will only honor REEF Promo Codes and no other promotion codes will be accepted in the REEF Order and Delivery Services. <br /><br />
            j. Gratuity. Gratuity is not automatically included in or added to orders. Gratuity can be given at the time of order or, at your discretion, in cash at the time your order is delivered. <br /><br />
            k. Product Information. WE ATTEMPT TO DISPLAY THE PRODUCTS AND OTHER MATERIALS AND INFORMATION AND OTHER PRODUCT INFORMATION YOU VIEW ON THE DIGITAL SERVICES AS ACCURATELY AND COMPLETELY AS POSSIBLE. HOWEVER, REEF DOES NOT GUARANTEE THE ACCURACY OF SUCH MATERIALS AND INFORMATION AND ARE NOT RESPONSIBLE FOR ANY CLAIMS ARISING OR RESULTING FROM YOUR RELIANCE THEREON. <br /><br />
            l. ADDITIONAL DISCLAIMER &amp; ALLERGY INFORMATION. YOU ARE SOLELY RESPONSIBLE FOR THE PROPER AND SAFE WASHING, HANDLING, PREPARATION, STORAGE, COOKING, USE AND CONSUMPTION OF THE PRODUCTS YOU RECEIVE THROUGH THE REEF ORDER AND DELIVERY SERVICES. REEF SHALL NOT BE RESPONSIBLE FOR NOTIFYING YOU OF PRODUCT RECALLS FOR ITEMS YOU HAVE PURCHASED THROUGH THE DIGITAL SERVICES. YOUR USE OF THE REEF ORDER AND DELIVERY SERVICES AND ITS GOODS IS AT YOUR OWN RISK. THE REEF ORDER AND DELIVERY SERVICES AND ITS GOODS ARE PROVIDED ON AN &ldquo;AS IS&rdquo;, &ldquo;AS AVAILABLE&rdquo; AND &ldquo;PRESENT CONDITION&rdquo; BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PROVIDED BY LAW, REEF HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSE AND WHOLESOMENESS. THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. <br /><br />
            YOU ARE ALSO SOLELY RESPONSIBLE FOR KNOWING ABOUT ANY FOOD ALLERGIES YOU MAY HAVE AND VERIFYING THE PRODUCTS AND THEIR CONTENTS BEFORE HANDLING, PREPARING, USING OR CONSUMING SUCH PRODUCTS. FURTHER, YOU UNDERSTAND, ACKNOWLEDGE AND AGREE THAT WE PREPARE, STORE, PORTION AND PACKAGE PRODUCTS CONTAINING ALL EIGHT (8) MAJOR U.S. ALLERGENS (MILK, WHEAT, EGG, SOY, FISH, SHELLFISH, PEANUTS AND TREENUTS) AND CANNOT GUARANTEE THAT CROSS-CONTAMINATION WILL NOT OCCUR BETWEEN PRODUCTS. THE GOODS YOU RECEIVE MAY HAVE SOME OR ALL OF THE ALLERGENS LISTED. IF YOU HAVE AN ALLERGIC REACTION OR OTHER ADVERSE HEALTH EVENT, CONTACT YOUR HEALTH CARE PROVIDER IMMEDIATELY. <br /><br />
            20.3 REEF Alcohol Services. Any use of any REEF Services relating to the purchase of alcohol beverages (&ldquo;REEF Alcohol Services&rdquo;) is subject to the following additional terms:<br /><br />
            a. REEF DOES NOT SELL ALCOHOL BEVERAGES. SALES OF ALCOHOL BEVERAGES ARE MADE BY DULY LICENSED, PARTICIPATING RETAIL MERCHANTS. <br /><br />
            b. REEF OFFERS INFORMATION AND A METHOD TO CONNECT DULY LICENSED PARTICIPATING RETAIL MERCHANTS TO YOU AND TO OTHER LAWFUL CUSTOMERS SEEKING TO PURCHASE ALCOHOL BEVERAGES. REEF DOES NOT, AND DOES NOT INTEND TO, MAKE SALES OF ALCOHOLIC BEVERAGES. EACH PARTICIPATING RETAIL MERCHANT IS THE SELLER OF RECORD FOR THE PARTICULAR ALCOHOL BEVERAGE PRODUCT(S) IT PROMOTES VIA THE REEF ALCOHOL SERVICES. REEF HAS NO RESPONSIBILITY OR LIABILITY FOR ANY ACTIONS OR OMISSIONS OF ANY PARTICIPATING RETAIL MERCHANT<br /><br />
            c. IN SOME INSTANCES, REEF MAY ITSELF OR THROUGH SEPARATE RELATED OR UNRELATED ENTITIES ACT AS A DELIVERY AGENT FOR THE PARTICIPATING RETAILER TO DELIVER ALCOHOL BEVERAGES TO YOU OR OTHER PURCHASERS OF LEGAL DRINKING AGE. <br /><br />
            d. REEF HAS NO RESPONSIBILITY OR LIABILITY FOR ANY ACTIONS OR OMISSIONS OF YOU OR ANY CUSTOMER THAT MAY RESULT, DIRECTLY OR INDIRECTLY, FROM THE PURCHASE AND/OR CONSUMPTION OF ALCOHOL BEVERAGES PROMOTED BY OR ACQUIRED THROUGH REEF ALCOHOL SERVICES.<br /><br />
            e. YOU AGREE THAT YOU WILL NOT USE THE REEF ALCOHOL SERVICES UNLESS YOU ARE 21 YEARS OF AGE OR OLDER, AND YOU WILL NOT FURNISH ALCOHOL BEVERAGES OBTAINED THROUGH THE REEF ALCOHOL SERVICES TO ANY PERSON WHO IS NOT A LAWFUL CONSUMER, INCLUDING ANYONE WHO IS (i) UNDER 21 YEARS OF AGE, OR (ii) OBVIOUSLY INTOXICATED, APPARENTLY INTOXICATED, OR KNOWN TO BE A HABITUAL DRUNKARD WITHIN THE MEANING OF THE LAWS GOVERNING THE STATE IN WHICH YOU RESIDE. <br /><br />
            f. Purchasing Protocols. Because REEF does not engage in the sale of alcohol beverages, all sales terms and conditions for products promoted through the REEF Alcohol Services are set and confirmed by the participating retail merchants selling those products. However, the following protocols apply to all sales facilitated by the REEF Alcohol Services:<br /><br />
            1. You must personally accept the delivery of your purchased products. <br /><br />
            2. You must provide the delivery agent with a government-issued photo identification confirming your age and identity upon delivery. This identification must be an original instrument, and not a copy, photo or facsimile of an identification document.<br /><br />
            3. The name on the government-issued photo identification must match the name on the credit card used to pay for the order.<br /><br />
            4. If you do not provide sufficient and valid identification to the delivery agent upon delivery (or if the identification is deemed by the delivery agent in their sole discretion, the expertise of which is acknowledged, to be fraudulent, false, or sufficiently in question to warrant rejection) or if the identification provided does not match the name on the credit card used by the purchaser to pay for the order, you agree that your order will be forfeited and the cost of the order will be paid to REEF in consideration for the time and effort required to prepare, package, and transport the order to you and back to the retailer. In such a case of an unverified or unverifiable identification, you will not be entitled to any refund or return.<br /><br />
            g. The REEF Alcohol Services are not meant to, directly or indirectly, provide any impermissible value/inducement by any alcohol beverage manufacturer, importer, or wholesaler to any alcohol beverage retailer.</p>
            <p>21. Contact Us<br /><br />
            If you have any questions about this Agreement, you may contact us by email at privacy@reeftechnology.com. <br /><br />
            </p>
        </div>
        <ScrollUp onClick={scrollTop} className="scroll-up" />
      </div>
      <Footer />
    </div>
  );
};
